import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'
import { getCodexUiStaticAsset, listCodexUiStaticAssetPaths } from '../src/codex/codex-ui-static.js'

describe('Codex UI static assets', () => {
  it('keeps generated asset bodies in sync with static source files', async () => {
    const [html, js, css] = await Promise.all([
      readFile(new URL('../src/ui/static/index.html', import.meta.url), 'utf8'),
      readFile(new URL('../src/ui/static/app.js', import.meta.url), 'utf8'),
      readFile(new URL('../src/ui/static/styles.css', import.meta.url), 'utf8')
    ])

    expect(getCodexUiStaticAsset('/')?.body).toBe(html)
    expect(getCodexUiStaticAsset('/app.js')?.body).toBe(js)
    expect(getCodexUiStaticAsset('/styles.css')?.body).toBe(css)
  })

  it('lists bundled static asset paths', () => {
    expect(listCodexUiStaticAssetPaths().sort()).toEqual(['/', '/app.js', '/styles.css'].sort())
  })

  it('returns static assets with content types', () => {
    expect(getCodexUiStaticAsset('/')?.contentType).toBe('text/html; charset=utf-8')
    expect(getCodexUiStaticAsset('/app.js')?.contentType).toBe('text/javascript; charset=utf-8')
    expect(getCodexUiStaticAsset('/styles.css')?.contentType).toBe('text/css; charset=utf-8')
  })

  it('returns undefined for missing static assets', () => {
    expect(getCodexUiStaticAsset('/missing')).toBeUndefined()
  })

  it('bundles expected initial UI content', () => {
    const html = getCodexUiStaticAsset('/')?.body

    expect(html).toContain('Cyrene Memory Console')
    expect(html).toContain('href="/styles.css"')
    expect(html).toContain('src="/app.js"')
    expect(html).toContain('data-app')
    expect(html).toContain('class="sidebar"')
    expect(html).toContain('class="main-shell"')
    expect(html).toContain('class="detail-rail"')
    expect(getCodexUiStaticAsset('/app.js')?.body).toContain('Write actions require confirmation and review hash')
    expect(getCodexUiStaticAsset('/styles.css')?.body).toContain('--coral: #cc785c')
    expect(getCodexUiStaticAsset('/styles.css')?.body).toContain('--canvas: #f4efe7')
  })

  it('wires static asset generation into plugin build', async () => {
    const buildScript = await readFile('scripts/build-plugin.mjs', 'utf8')
    const generatedSource = await readFile('src/codex/codex-ui-static.generated.ts', 'utf8')

    expect(buildScript).toContain('generate-ui-static.mjs')
    expect(generatedSource).toContain('Generated by scripts/generate-ui-static.mjs')
  })
})
