import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'
import { getCodexUiStaticAsset, listCodexUiStaticAssetPaths } from '../src/codex/codex-ui-static.js'

describe('Codex UI static assets', () => {
  it('lists bundled static asset paths', () => {
    expect(listCodexUiStaticAssetPaths().sort()).toEqual(['/', '/app.js', '/styles.css'].sort())
  })

  it('returns static assets with content types', () => {
    expect(getCodexUiStaticAsset('/')?.contentType).toBe('text/html; charset=utf-8')
    expect(getCodexUiStaticAsset('/app.js')?.contentType).toBe('text/javascript; charset=utf-8')
    expect(getCodexUiStaticAsset('/styles.css')?.contentType).toBe('text/css; charset=utf-8')
  })

  it('returns undefined for missing static assets', () => {
    expect(getCodexUiStaticAsset('/missing')).toBeUndefined()
  })

  it('bundles expected initial UI content', () => {
    expect(getCodexUiStaticAsset('/')?.body).toContain('Cyrene Memory Console')
    expect(getCodexUiStaticAsset('/app.js')?.body).toContain('Write actions disabled in v1')
    expect(getCodexUiStaticAsset('/styles.css')?.body).toContain('--coral: #cc785c')
    expect(getCodexUiStaticAsset('/styles.css')?.body).toContain('--canvas: #f4efe7')
  })

  it('wires static asset generation into plugin build', async () => {
    const buildScript = await readFile('scripts/build-plugin.mjs', 'utf8')
    const generatedSource = await readFile('src/codex/codex-ui-static.generated.ts', 'utf8')

    expect(buildScript).toContain('generate-ui-static.mjs')
    expect(generatedSource).toContain('Generated by scripts/generate-ui-static.mjs')
  })
})
