// Generated by scripts/generate-ui-static.mjs. Do not edit manually.

export interface CodexUiStaticAsset {
  contentType: string
  body: string
}

export const CODEX_UI_STATIC_ASSETS: Record<string, CodexUiStaticAsset> = {
  "/": {
    "contentType": "text/html; charset=utf-8",
    "body": "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <title>Cyrene Memory Console</title>\n    <link rel=\"stylesheet\" href=\"/styles.css\">\n  </head>\n  <body>\n    <div class=\"app-shell\" data-app>\n      <aside class=\"sidebar\" aria-label=\"Memory navigation\">\n        <h1>Cyrene Memory Console</h1>\n      </aside>\n      <main class=\"main-shell\">\n        <section aria-label=\"Memory review queue\"></section>\n      </main>\n      <aside class=\"detail-rail\" aria-label=\"Memory detail\"></aside>\n    </div>\n    <script type=\"module\" src=\"/app.js\"></script>\n  </body>\n</html>\n"
  },
  "/app.js": {
    "contentType": "text/javascript; charset=utf-8",
    "body": "export const WRITE_ACTION_DISABLED_COPY = 'Write actions disabled in v1'\n\nconst app = document.querySelector('[data-app]')\n\nif (app) {\n  app.dataset.ready = 'true'\n}\n"
  },
  "/styles.css": {
    "contentType": "text/css; charset=utf-8",
    "body": ":root {\n  --canvas: #f4efe7;\n  --surface: #f4efe7;\n  --surface-inset: #efe4d6;\n  --ink: #181715;\n  --body: #5f584f;\n  --muted: #8d8479;\n  --coral: #cc785c;\n  --teal: #5db8a6;\n  --amber: #d4a017;\n  --red: #c64545;\n  --line: rgba(118, 91, 70, 0.14);\n}\n\n* {\n  box-sizing: border-box;\n}\n\nbody {\n  margin: 0;\n  min-height: 100vh;\n  background: var(--canvas);\n  color: var(--ink);\n  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;\n}\n\n.app-shell {\n  display: grid;\n  grid-template-columns: minmax(220px, 280px) minmax(0, 1fr) minmax(240px, 320px);\n  min-height: 100vh;\n}\n\n.sidebar,\n.main-shell,\n.detail-rail {\n  min-width: 0;\n  border-right: 1px solid var(--line);\n}\n\n.sidebar,\n.detail-rail {\n  background: var(--surface-inset);\n  padding: 24px;\n}\n\n.main-shell {\n  background: var(--surface);\n  padding: 24px;\n}\n\nh1 {\n  margin: 0;\n  color: var(--ink);\n  font-size: 18px;\n  font-weight: 650;\n  line-height: 1.2;\n}\n"
  }
}
