import { randomUUID } from 'node:crypto'
import { open, rename, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { assertMemoryProjectionTargetsSafe } from '../memory/memory-exporter.js'
import {
  isLowRiskLifecycleMemory,
  validateSemanticMemoryLifecycle
} from '../memory/memory-lifecycle.js'
import type { SemanticMemory } from '../memory/types.js'

const GENERATED_HEADER = '<!-- Generated by Cyrene Continuity v1.5. Do not edit manually. -->'
const MODEL_PROFILE_FILE = 'MODEL_PROFILE.md'

export async function assertLifecycleProfileTargetSafe(memoryRoot: string): Promise<string> {
  return assertMemoryProjectionTargetsSafe(memoryRoot)
}

export function formatLifecycleProfileFromCoreMemory(input: {
  scope: 'project' | 'global'
  memories: SemanticMemory[]
}): string {
  const coreTier = input.scope === 'global' ? 'global_core' : 'project_core'
  const core = input.memories
    .filter((memory) =>
      memory.status === 'active' &&
      memory.confidenceTier === coreTier &&
      isLowRiskLifecycleMemory(memory) &&
      validateSemanticMemoryLifecycle(memory).length === 0
    )
    .map((memory) => sanitizeProfileContent(memory.content))
    .filter((content): content is string => content !== null)
    .sort((left, right) => left.localeCompare(right))

  const lines = [
    GENERATED_HEADER,
    '',
    '# Cyrene Model Profile',
    '',
    '## Always Apply',
    ''
  ]

  if (core.length === 0) {
    lines.push('- None.')
  } else {
    for (const content of core) {
      lines.push(`- ${content}`)
    }
  }

  lines.push('')
  return `${lines.join('\n').trimEnd()}\n`
}

export async function writeLifecycleProfileFromCoreMemory(input: {
  memoryRoot: string
  scope: 'project' | 'global'
  memories: SemanticMemory[]
}): Promise<string> {
  const root = await assertLifecycleProfileTargetSafe(input.memoryRoot)
  const content = formatLifecycleProfileFromCoreMemory({
    scope: input.scope,
    memories: input.memories
  })
  await writeSafeGeneratedProfile(root, content)
  return content
}

async function writeSafeGeneratedProfile(memoryRoot: string, content: string): Promise<void> {
  await assertLifecycleProfileTargetSafe(memoryRoot)
  const targetPath = join(memoryRoot, MODEL_PROFILE_FILE)
  const tempPath = join(memoryRoot, `.${MODEL_PROFILE_FILE}.${process.pid}.${Date.now()}.${randomUUID()}.tmp`)
  const file = await open(tempPath, 'wx')

  try {
    await file.writeFile(content, 'utf8')
  } catch (error) {
    await file.close()
    await rm(tempPath, { force: true })
    throw error
  }

  await file.close()
  await assertLifecycleProfileTargetSafe(memoryRoot)

  try {
    await rename(tempPath, targetPath)
  } catch (error) {
    await rm(tempPath, { force: true })
    throw error
  }
}

function sanitizeProfileContent(content: string): string | null {
  const sanitized = content
    .replace(/\b(Bearer\s+)[A-Za-z0-9._~+/=-]{12,}\b/g, '$1[REDACTED]')
    .replace(/\b(password|passwd|credential|secret|api[_ -]?key|token|private key|ssh key)\s*[:=]\s*\S+/gi, '$1=[REDACTED]')
    .replace(/\b[A-Fa-f0-9]{32,}\b/g, '[REDACTED]')
    .replace(/\s+/g, ' ')
    .trim()

  return sanitized === '' ? null : sanitized
}
